### ISSUE TITLE
bug: dependency ceiling markdown>=3.3,<3.6 acts as a timebomb

### ISSUE THREAD

**Issue by ssbarnea** [mkdocstrings/python#143]
### Description of the bug

This dependency "time-bomb" was recently introduced in https://github.com/mkdocstrings/python/commit/cd93ee31418a2752667d43bb5a05d22284522c24 - i supposed as it was known that the new ones cased some failures.

### Expected behavior

Be compatible with latest versions of its dependencies, especially as other mkdocs plugins might rely newer versions, so a conflict could happen.

Usually I prefer to have a different pipeline that tests unreleased versions of major major dependencies, so I know when they are about the break before they release. This sorts the problems of having to add ceiling when problems are encountered.

### Environment information

```bash
python -m mkdocstrings_handlers.python.debug  # | xclip -selection clipboard
```

PASTE OUTPUT HERE

**Comment by ssbarnea** [comment]
Yep, it should support 3.6. I only mentioned the other things for the future. To avoid similar problem when 3.7 is released.

**Comment by pawamoy** [comment]
Yup, I usually never cap my dependencies.

> Usually I prefer to have a different pipeline that tests unreleased versions of major major dependencies, so I know when they are about the break before they release. This sorts the problems of having to add ceiling when problems are encountered.

In this particular case, I knew 3.6 would break mkdocstrings-python before it was released, so I added the cap before the release. Since this won't change in 3.7+, I didn't just exclude 3.6 with `!=3.6`. Also, the breakage is not easily detected, at least not with our current test suite. I have it in my backlog to add end-to-end tests to facilitate detecting such breakages. Lots of work :smile:
