### ISSUE TITLE
Parameters and Returns headings are not visible

### ISSUE THREAD

**Issue by francois-rozet** [mkdocstrings/python#17]
**Is your feature request related to a problem? Please describe.**

"Parameters" and "Returns" headings are simple HTML paragraphes without any CSS class. They currently just look like plain text and there is no way to style them.

**Describe the solution you'd like**

The easiest solution is to assign a CSS class to these headings such that we can style them arbitrarily.
Additionally, it would be better if they were actual HTML headings (and we could choose the level).
The colons also look rather unpolished.

**Comment by pawamoy** [comment]
Would you like to send a PR? You'd need to update this

https://github.com/mkdocstrings/python/blob/f2122d7fa119ed055ffe2b2bac72d2c643daca1c/src/mkdocstrings_handlers/python/templates/material/_base/docstring/parameters.html#L3

to something like `<span class="doc-section-title">` instead of `<strong>` (in every docstring template of course).

**Comment by francois-rozet** [comment]
Sure, I'll try to do that. By the way, currently there is not even `<strong>` around the parameters and returns if the section style is `list`.

https://github.com/mkdocstrings/python/blob/d5ea1c5cf7884d8c019145f73685a84218e69840/src/mkdocstrings_handlers/python/templates/material/_base/docstring/parameters.html#L39

**Comment by pawamoy** [comment]
Yeah there are probably discrepancies between all the different sections, sections styles and themes. I should probably start to create tables like the Griffe ones (https://mkdocstrings.github.io/griffe/docstrings/) to keep track of everything.
