### ISSUE TITLE
Non-Primitive Return Types are Incorrectly Formatted

### ISSUE THREAD

**Issue by w11wo** [mkdocstrings/python#57]
**Describe the bug**
`mkdocstrings-python` handler does not correctly format non-primitive return types in the generated documentation table, although this functionality remains correct for native types such as `str`, `int`, `float`, etc.

This is in contrast to the legacy `mkdocstrings-python-legacy` handler that generates the return types correctly.

**To Reproduce**
Have a return type of `typing.List` (from `typing` package), for example, and notice that the generated documentation table is incorrect. It will have a description of "typing.List {user-added docstrings}", and optionally also gets incorrectly treated as "Name".

**Expected behavior**
Return type is not repeated and not considered as name, just like in `mkdocstrings-python-legacy`.

**Screenshots**
![mkdocstrings_python_return_issue](https://user-images.githubusercontent.com/23167175/215437640-79992b34-8c11-4b62-bb2d-0e00b72cb415.jpg)

**System (please complete the following information):**
- `mkdocstrings-python` version: 0.8.3
- Python version: 3.8.15
- OS: Linux

**Additional context**
An example of the incorrectly generated documentation table can be found [here](https://bookbot-kids.github.io/speechline/reference/models/transcribers/wav2vec2_transcriber/#speechline.transcribers.Wav2Vec2Transcriber.predict).

**Comment by pawamoy** [comment]
Hey @w11wo, thanks for the nice report!

So, users previously asked that we support named return values. To support that, we had to use the same syntax as for parameters: `name (type): Description.`. It means that a return section with `int: An integer.` will be parsed as `name=int` and `description=An integer.`. You would have to wrap `int` with parentheses to have it parsed as the type instead of the name: `(int): An integer.`.

With that said, I understand this is unexpected and non-standard, so my plan is to make this configurable. I'll eventually get to it :smile:

**Comment by pawamoy** [comment]
Also note that you don't need to write the type in the docstring if you add a return annotation to the signature: `def func() -> int: ...`

**Comment by w11wo** [comment]
Thanks for the clear explanation @pawamoy!

I agree that it will be great to have that option configurable, I think it would be beneficial for a lot of people. Looking forward to the update 😄

**Comment by pawamoy** [comment]
This has been implemented for quite some time now, and documented here: https://mkdocstrings.github.io/griffe/docstrings/#google-options. Closing :slightly_smiling_face:
