### ISSUE TITLE
Cross links to inherited members link to parent class

### ISSUE THREAD

**Issue by ianspektor** [mkdocstrings/python#91]
**Describe the bug**
In my `temporian` library I have `class EventSet(EventSetOperationsMixin)`. If I write a cross-link to a member in `EventSet` inherited from `EventSetOperationsMixin` (such as `[EventSet.begin()][temporian.EventSet.begin]`), the link leads to the parent class' page instead of the child's.

**To Reproduce**
Example is up at https://temporian--206.org.readthedocs.build/en/206/reference/#operators.
Search for EventSet.begin(), click the link, it takes you to https://temporian--206.org.readthedocs.build/en/206/reference/temporian/internals/EventSetOperationsMixin/#temporian.core.mixins.EventSetOperationsMixin.begin instead of https://temporian--206.org.readthedocs.build/en/206/reference/temporian/EventSet/#temporian.implementation.numpy.data.event_set.EventSet.begin 
Docs source for that file: https://github.com/google/temporian/blob/op-chaining/docs/src/reference/index.md 

**Expected behavior**
Link should take to the child class that I cross linked to, not its parent that defines the method.

**Screenshots**
-

**System (please complete the following information):**
- `mkdocstrings-python` version: 1.2.1
- Python version: 3.9.10
- OS: MacOS/Linux same behavior

**Additional context**
-

**Comment by pawamoy** [comment]
Thanks for the report. Good catch again. That actually is a symptom of #90: since the `temporian.EventSet` members are rendered with their actual object path instead of the alias path, when time comes to update cross-ref links, the `temporian.EventSet.begin` id does not exist in the docs, and therefore we fallback on a known id which is `temporian.core.mixins.EventSetOperationsMixin.begin`.

Fixing #90 should fix this issue too :slightly_smiling_face:

**Comment by pawamoy** [comment]
Hello, this should be fixed with mkdocstrings-python 1.5.1 and Griffe 0.35! Please open a new ticket if you have any issues!

**Comment by ianspektor** [comment]
Indeed fixed. Thanks! :)
